inheritDefault: true
mutations:
  # Results in `default-src 'self'`
  - mode: "set"
    directive: "default-src"
    sources:
      - "'nonce-proxy'"

  - mode: "extend"
    directive: "img-src"
    sources:
      - "'nonce-proxy'"
      - "data:"

  - mode: "set"
    directive: "script-src"
    sources:
      - "'nonce-proxy'"

  - mode: "set"
    directive: "script-src-elem"
    sources:
      - "'nonce-proxy'"

  - mode: "set"
    directive: "font-src"
    sources:
      - "'self'"

  - mode: "extend"
    directive: "media-src"
    sources:
      - "'self'"
  # Results in `worker-src blob:`
  #- mode: "set"
  #  directive: "worker-src"
  #  sources:
   #   - "blob:"
  #unsafe-inline TODO - How can i add this
# Inherits default site-unspecific frontend policy mutations (enabled per default)
#enforce:
#  inheritDefault: true
##  mutations: {}
  # for disabling the reporting endpoint for a particular site
#  reportingUrl: false
  # for using a different external reporting endpoint
#  reportingUrl: https://reporting.example.org/
  # for using the default local reporting endpoint (default)

#####