inheritDefault: true
mutations:
  - mode: "set"
    directive: "default-src"
    sources:
      - "example-13.ddev.site"

  - mode: "extend"
    directive: "default-src"
    sources:
      - "'nonce-proxy'"

  - mode: "set"
    directive: "script-src-elem"
    sources:
      - "'nonce-proxy'" 

  - mode: "extend"
    directive: "img-src"
    sources:
      - data:;

  - mode: "set"
    directive: "script-src"
    sources:
      - "'unsafe-eval'"

  - mode: "extend"
    directive: "font-src"
    sources:
      - "'nonce-proxy'"       

  - mode: "reduce"
    directive: "font-src"
    sources:
      - http://example-13.ddev.site

  - mode: "reduce"
    directive: "style-src-attr"
    sources:
      - "'unsafe-inline'"

