# Inherits default site-unspecific frontend policy mutations (enabled per default)
inheritDefault: true
mutations:
  # Results in `default-src 'self'`
  - mode: "set"
    directive: "default-src"
    sources:
      - "'self'"
      - "https://example-13.ddev.site"

  # Extends the ancestor directive ('default-src'),
  # thus reuses 'self' and adds additional sources
  # Results in `img-src 'self' data: https://*.typo3.org`
  - mode: "extend"
    directive: "img-src"
    sources:
      - "'self'"
      - "data:"
      - "https://example-13.ddev.site"

  - mode: "extend"
    directive: "font-src"
    sources:
      - "'self'"
      - "https://example-13.ddev.site"

  # Extends the ancestor directive ('default-src'),
  # thus reuses 'self' and adds additional sources
  # Results in `script-src 'self' 'nonce-[random]'`
  # ('nonce-proxy' is substituted when compiling the policy)
  - mode: "extend"
    directive: "script-src"
    sources:
      - "'nonce-proxy'"
      - "'self'"
      - "https://example-13.ddev.site"

  # Results in `worker-src blob:`
  #- mode: "set"
  #  directive: "worker-src"
  #  sources:
   #   - "blob:"
  #unsafe-inline TODO - How can i add this