name: t3example/btslider
label: t3example/btslider
description: 'Carousel/Imageslider with Bootstrap'
basics:
  #- t3example/Appearance
  - t3example/Links
group: ContentBlocks
prefixFields: true
prefixType: full
fields:
  - identifier: header
    useExistingField: true
    label: Pluginbeschreibung für TYPO3 BE
  - identifier: tab_1
    type: Tab
  - identifier: palette_1
    type: Palette
    label: Palette 1
    description: My palette description
    fields:
      - identifier: modus
        type: Select
        renderType: selectMultipleSideBySide
        maxitems: 1
        items:
        - label: slide
          value: 0
        - label: fade
          value: 1
      - type: Linebreak      
      - identifier: control
        type: Checkbox
        renderType: checkboxLabeledToggle
        default: 
        items:
        - label: 'Prev / Next Button einblenden'
          labelChecked: 'On'
          labelUnchecked: 'Out'
          invertStateDisplay: true
      - type: Linebreak      
      - identifier: indicator
        type: Checkbox
        renderType: checkboxLabeledToggle
        #default: 0
        items:
        - label: 'Slideindikatoren anzeigen / Bulletpoints'
          labelChecked: 'On'
          labelUnchecked: 'Out'
          invertStateDisplay: true
  - identifier: tab_2
    type: Tab
  - identifier: palette_2
    type: Palette
    label: Slideimages anlegen
    fields:
  - identifier: slides
    type: Collection
    label: Slideitems mit Textslogans anlegen
    fields:
      - identifier: image
        label: Bild
        type: File
        allowed: common-image-types
      - identifier: palette_3
        type: Palette
        label: Slogan zum Bild - animiert
      - identifier: slogan_big
        label: Slogan Groß
        type: Textarea
        placeholder: Text groß - wird einzeln animiert
        rows: 10
      - identifier: slogan_small
        label: Slogan Klein
        type: Textarea
        placeholder: Text klein - wird einzeln animiert
        rows: 10
      - identifier: links
        label: Call to Action Link
        type: Collection
        labelField: link_title
        fields:
          - identifier: link
            type: Link
            autocomplete: true
            allowedTypes:
              - page
              - url
              - file
            max: 150
          - identifier: link_title
            type: Text