name: t3example/bttabs
title: t3example/bttabs
description: 'Tabs width Bootstrap'
basics:
  - t3example/Appearance
  - t3example/Links
group: ContentBlocks
saveAndClose: true
prefixFields: true
prefixType: full
fields:
  - identifier: cb_header
    label: Pluginbeschreibung für TYPO3 BE
    type: Text
  - identifier: tab_1
    type: Tab
    label: Tab Einstellungen
  - identifier: palette_41
    type: Palette
    fields:
      - identifier: choose-display
        type: Select
        renderType: selectSingle
        label: Ansicht zwischen Tabs & Pills auswählen
        default: 'one'
        items:
          - label: 'Tabs (eckig)'
            value: one
          - label: 'Pills (abgerundet)'
            value: two
  - identifier: tab_2
    type: Tab
    label: Tab Items
  - identifier: palette_42
    type: Palette
    fields:
      - identifier: tabsets
        type: Collection
        label: Tabitem anlegen
        foreign_table: tx_example_textimage
        shareAcrossTables: true
        shareAcrossFields: true
