styles:
  templates:
    #layoutRootPath: EXT:site_package/Resources/Private/Layouts/ContentElements
    #partialRootPath: EXT:site_package/Resources/Private/Partials/ContentElements
    #templateRootPath: EXT:site_package/Resources/Private/Templates/ContentElements
  content:
    textmedia:
      maxW: 1200
      maxWInText: 600
      linkWrap:
        lightboxEnabled: true
        lightboxCssClass: lightbox