name: t3example/btherowithvideo
title: t3example/btherowithvideo
description: 'Bootstrap Hero Section with BGVideo'
group: ContentBlocks
saveAndClose: true
prefixFields: true
prefixType: full
fields:
  - identifier: cb_header
    type: Text
    label: Pluginbeschreibung für TYPO3 BE
  - identifier: tab_1
    type: Tab
    label: Video + Einstellungen
  - identifier: palette_411
    type: Palette
    label: Video + Einstellungen
    description: Das Video kann im Loop ablaufen, Automatisch gestartet und stumm geschaltet werden 
    fields:
      - identifier: video
        type: File
        extendedPalette: false
        allowed: mp4, ogg, youtube, vimeo
      - type: Linebreak   
      -  identifier: autoplay
         label: 'Video starten'
         description: Video wird automatisch beim laden gestartet
         type: Checkbox
         renderType: checkboxLabeledToggle
         default: '1'
         items:
           - label: ''
             labelUnchecked: 'Nein'
             labelChecked: 'Ja'
             invertStateDisplay: false 
      -  identifier: autostop
         label: 'Video kann bei Klick ins Video gestopt werden'
         description: Das Video kann bei Klick in das Video gestopt oder gestartet werden.
         type: Checkbox
         renderType: checkboxLabeledToggle
         default: '1'
         items:
           - label: ''
             labelUnchecked: 'Nein'
             labelChecked: 'Ja'
             invertStateDisplay: false        
      -  identifier: loop
         label: 'Video loopen lassen'
         description: Das Video läuft in einer Dauerschleife.
         type: Checkbox
         renderType: checkboxLabeledToggle
         default: '1'
         items:
           - label: ''
             labelUnchecked: 'Nein'
             labelChecked: 'Ja'
             invertStateDisplay: false
      -  identifier: muted
         label: 'Video stumm stellen'
         description: Das Video ist per default stumm geschaltet.
         type: Checkbox
         renderType: checkboxLabeledToggle
         default: '1'
         items:
           - label: ''
             labelUnchecked: 'Nein'
             labelChecked: 'Ja'
             invertStateDisplay: true      
  - identifier: tab_2
    type: Tab
    label: Text und Positionierung
  - identifier: palette_412
    type: Palette
    label: Texte
    description: Teasertext, Headline und Positionierung des Teasers, ggf. einen CTA Button
    fields:
      - identifier: teaserheadline
        type: Text
        label: Überschrift des Teasers
        description: Headline wird mit h1 angezeigt
        placeholder: Überschrift 
      - identifier: teasertext
        type: Textarea
        label: Teasertext
        enableRichtext: true
        richtextConfiguration: simple
        description: Dieser Text wird auf Mobilen Geräten nicht ausgegeben.
        placeholder: Text eingeben
      - type: Linebreak
      - identifier: links
        label: Call to Action Link
        description: Bis zu 3 einzelne links können bei Bedarf definiert werden.
        type: Collection
        labelField: link_title
        fields:
          - identifier: cta
            label: Linktext
            useExistingField: true
            type: Text
            placeholder: Call to Action Text
          - identifier: link
            label: Linksziel
            type: Link
            autocomplete: true
            allowedTypes:
              - page
              - url
              - file
            max: 3
          - identifier: link_title
            label: Titletext für den Link
            type: Text     
      - identifier: teaserposition
        type: Select
        renderType: selectSingle
        label: Positionierung des Teasers
        description: Nur die headline wird auf Mobilen Geräten unten ausgegeben.
        default: 1
        items:
          - label: 'mittig'
            value: top-md-50 start-md-50 translate-middle
          - label: 'Oben - Links'
            value: top-md-20px start-md-20px
          - label: 'Oben - Rechts'
            value: top-md-20px end-md-20px
          - label: 'Unten - Links'
            value: bottom-md-20px start-md-20px
          - label: 'Unten - Rechts'
            value: bottom-md-20px end-md-20px
      - identifier: linkposition
        label: Linkposition
        description: Wird unterhalb des Teasertextes positioniert
        type: Select
        renderType: selectSingle
        items:
          - label: 'Links'
            value: justify-content-start
          - label: 'Rechts'
            value: justify-content-end 
          - label: 'Mittig'
            value: justify-content-center    
