name: t3example/btdetailsaccordion
title: t3example/btdetailsaccordion
typeName: t3example_btdetailsaccordion
description: 'Accordion with Bootstrap'
basics:
  - t3example/Appearance
  - t3example/Links
group: ContentBlocks
saveAndClose: true
prefixFields: true
prefixType: full
fields:
  - identifier: cb_header
    label: Pluginbeschreibung für TYPO3 BE
    type: Text
  - identifier: tab_1
    type: Tab
    label: Accordion Einstellungen
  - identifier: palette_24
    type: Palette
  - identifier: choose-icon
    type: Select
    renderType: selectSingle
    label: Close/Open Icon auswählen
    default: 'one'
    items:
      - label: 'Mit Pfeilchen'
        value: one
      - label: 'Mit Plus - Minus Zeichen'
        value: two
  - identifier: tab_2
    type: Tab
    label: Accordion Items
  - identifier: palette_25
    type: Palette
  - identifier: accordiondetailsset
    type: Collection
    label: Accordionitems anlegen
    foreign_table: tx_example_textimage
    shareAcrossTables: true
    shareAcrossFields: true